---
{{- if .Values.alertmanager.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-alertmanager
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cortex: alertmanager
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    app: {{ template "name" . }}-alertmanager
    release: {{ .Release.Name }}
{{- end }}
