---
{{- if .Values.configs.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-configs
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cortex: configs
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    app: {{ template "name" . }}-configs
    release: {{ .Release.Name }}
{{- end }}
