apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-consul
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cortex: consul
spec:
  ports:
  - name: http
    port: 8500
  selector:
    app: {{ template "name" . }}-consul
    release: {{ .Release.Name }}
