---
{{- if .Values.grafana.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-grafana
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cortex: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "name" . }}-grafana
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-grafana
        release: {{ .Release.Name }}
        cortex: grafana
    {{- with .Values.grafana.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      tolerations:
{{ toYaml .Values.grafana.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.grafana.affinity | indent 8 }}
      containers:
      - name: grafana
        image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        resources:
{{ toYaml .Values.distributor.resources | indent 10 }}
        volumeMounts:
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: {{ template "fullname" . }}-grafana
{{- end }}
                