---
{{- if .Values.nginx.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-nginx
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app: {{ template "name" . }}-nginx
    cortex: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
      cortex: nginx
  template:
    metadata:
      labels:
        name: nginx
        cortex: nginx
    {{- with .Values.nginx.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      tolerations:
{{ toYaml .Values.nginx.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.nginx.affinity | indent 8 }}
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "fullname" . }}-nginx
{{- end }}
