---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-table-manager
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cortex: table-manager
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    app: {{ template "name" . }}-table-manager
    release: {{ .Release.Name }}
